### ISSUE TITLE
Usage of Jenkins

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [bounswe/bounswe2017group10#118]
I think we should use jenkins for our repository so that when someone sends a pr they can see if tests pass, also since tests are cumulative it will let us know if any of the previous tests failed as well.

**Comment by yigitozkavci** [comment]
How do you suggest on proceeding with this @SaitTalhaNisanci? Maybe we can consider TravisCI since it's free for open-source projects and **very** easy to integrate. We can use TravisCI to run our tests, and Jenkins to manage our deployments.

**Comment by yigitozkavci** [comment]
@kutaycandan Do you have any suggestions on a platform for running our tests on each commit and pull request? We can try things out for the sake of learning :)

**Comment by SaitTalhaNisanci** [comment]
@yigitozkavci  Sure,we can use TravisCI.

**Comment by eozd** [comment]
I can take a loot at Travis CI integration.

**Comment by yigitozkavci** [comment]
We have a problem there. For Travis, we need to register our GitHub application and want permission for it for `bounswe` organisation, which doesn't seem to be possible.

We can make our deployments and tests via Jenkins now, and I'm trying to integrate it with Github in order to see our test results here.

**Comment by yigitozkavci** [comment]
It's practically not a good idea to make Jenkins build branches other than master, since we're aiming to use it only for deployment purposes and it currently works just fine for that purpose.

Can you have a look at Travis @eozd? Especially we need to see if we can make the authentication work since this repo belongs to the `bounswe` organisation

**Comment by eozd** [comment]
@yigitozkavci I will have a look at it, and see if we can come up with something to handle the authentication problem you've mentioned.

**Comment by yigitozkavci** [comment]
With Travis running our tests and Jenkins deploys the application, I'm closing this.
