### ISSUE TITLE
API endpoints

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [bounswe/bounswe2017group10#147]
Would it be better to include api version in our endpoints ? 

For example right now we have /api/auth/ and it doesn't specify any version. So changing api could cause some problems in the future for the ones that use the previous api. With version it could be something like /api/v0/auth/ and when we change the api we can create a new endpoint such as: /api/v1/auth.

**Comment by YmirKhang** [comment]
I don't think that this is very important. But it might be useful. Two things:

- If we create endpoints for all api versions like api/v1.1/auth/ we could also redirect all the api calls from api/auth/ to api/<latest_v>/auth. (Better for the end user)

- Could also warn old api users with a http response or with a status code.

**Comment by yigitozkavci** [comment]
What do you mean by "old api users"? @emir350z AFAIK we don't, and probably won't have api users other than our clients (ie. mobile and web clients)

Api versioning is practically hard to maintain, that's why most of the public APIs out there uses versions of v1 and v2, and rarely you can see v3. Reason for that is you need to code each version separately, and figure out shared code parts across different versions. That's a legitimate burden for back-end application.

I am okay with using api versioning, but just for convenience; not to change it on every major release. In other words, api versioning that will rarely change is fine but one that changes on every new endpoint implementation will be hard to maintain IMO

**Comment by SaitTalhaNisanci** [comment]
I am closing this issue. Currently we dont have versioning in our apis.
