### ISSUE TITLE
Media items

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [bounswe/bounswe2017group10#166]
We should have media items in our cultural heritage item model. While adding an media item to a cultural heritage item I can think of 2 choices:
- We can have an endpoint to create a media item and using that endpoint client will create a media item and put its **id** or **ids**, if there are more than one media items, to the field 'media_items' in json.
- Or instead of having a separate endpoint for media items client can directly give the related information to  cultural heritage item's 'media_items' field. 

Which one do you guys think is better ?

**Comment by kutaycandan** [comment]
I think first one is better.

**Comment by eozd** [comment]
We should account for the possibility of adding more media items to a culture heritage item after it is created. In that case, having a separate endpoint for uploading media items might be better.

Maybe it would be possible to link this media item to a cultural heritage item via this separate endpoint by passing a culture heritage item id. So, the workflow for creating a culture heritage item with 2 media items would be
1. create cultural_heritage_item --> get its ID.
2. create media item; send the obtained ID at 1.
3. create media item; send the obtained ID at 1.

2 and 3 may also be combined and we can have a separate endpoint for uploading multiple media items at once. This might improve performance, since we plan to have several or dozens of media items per cultural heritage item.

**Comment by SaitTalhaNisanci** [comment]
I was thinking of the order like this:

1. Create media item/s --> say, their ids , id1,id2....idN
2. Add  id1,id2....idN to the cultural heritage item's **media_items** field.

**Comment by SaitTalhaNisanci** [comment]
I think it is better to store ids of media items in cultural heritage items than storing cultural heritage item's id in media items.  The former will be faster. What do you think @eozd

**Comment by eozd** [comment]
That is also possible. Then we can have an endpoint that takes a media item array and returns an array of ids. Later, we can send this array of ids inside culture item

**Comment by eozd** [comment]
@SaitTalhaNisanci Are we going to send URLs as media items or raw image/video data?

**Comment by eozd** [comment]
Another question, how are we going to handle adding more media items to a culture item?
