### ISSUE TITLE
Handle testing of API

### ISSUE THREAD

**Issue by YmirKhang** [bounswe/bounswe2017group10#85]
We should do the followings for our API project:

- [x] Documentation with use cases

- [x] Exception handling for API methods

- [x] Unit tests for the API

**Comment by egemahlec** [comment]
@emir350z, More items we should discuss. Therefore, I added some more topics.

We should do the followings for our API project:

- [ ] We need to write API Documentation

- [ ] We need to be sure that we are catching exceptions and take correct actions depend on the exception.

- [ ] We need to write unit test for our API.

- [x] We need to write test cases for **our project**. (Acceptance Test) (not only for our API, for our project)

- [ ] We need to update "How to Create Issue Spec" by adding some tags so that we can categorize the bugs whether it is showstopper or running change.

I think we need to create different issues to track these items. In the meeting, we can discuss these items and we can assign these topics so that every assignees can create his/her issue.
